### ISSUE TITLE
Cursor is placed before in-text citation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#17]
When I insert a citation in APA, my cursor ends up before the citation. Not sure if it's possible to place it after, but it's annoying this way.

**Comment by adomasven** [comment]
We actually can't do this as easily as I initially thought.

**Comment by adomasven** [comment]
https://forums.zotero.org/discussion/75582/googledoc-zotero-inserts-citations-before-the-cursor
