### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#19]
Since the Safari connector was finally accepted into the Extensions Gallery, we might as well look into whether Google Docs support works in Safari and, if not, if it's easy to get it working. I believe updates to Gallery extensions are approved more quickly, so we'll probably have a chance to push out at least a couple updates before they stop accepting updates in December 2018 (but we should obviously wait until we're pretty sure we have a stable build before submitting).

Of course, if Google Docs changes after December 2018 in a way that breaks something, we wouldn't be able to do anything to fix it, which makes me a little nervous, but people would still be able to turn off Google Docs integration. That would probably just prevent it from working, not break Google Docs, but we could consider building in a kill switch in the client ping if we were concerned.

**Comment by dstillman** [comment]
Apparently the version of 5.0.41 we submitted has the setting in the prefs — though off by default, I believe, and marked as experimental. But the basics, at least for APA, seem to work.

**Comment by adomasven** [comment]
Great news! I haven't tested Safari support recently, but I think the current version should just work without issues. Either way, I'll do some testing and report.

**Comment by adomasven** [comment]
Current version works in safari without modification
