### ISSUE TITLE
Too many changes applied before saving document.

### ISSUE THREAD

**Issue by 1im1** [zotero/zotero-google-docs-integration#20]
When trying to refresh the references in google docs with the 5.0.49 Zotero connector in Firefox 63 it fails with the following error message:

> Zotero experienced an error updating your document.
> 
> Too many changes applied before saving document. Please save changes in smaller batches using Document.saveAndClose(), then reopen the document with Document.openById().

The error message seems to stem from the google scripting api: [https://developers.google.com/apps-script/reference/document/document].

The document is about 25 pages and has 100 references.

Any ideas of a workaround?

**Comment by 1im1** [comment]
No it wasn't stuck totally it just threw the error message after about 5 minutes and didn't update the references. Unfortunately I cannot share that document, but I spend yesterday trying to reproduce with a similar length document with the same references and the same size figures, but that just works fine. Slow but works. So will try further to reproduce the error and then send a link to share it.

**Comment by ntraut** [comment]
Hello, I have the same problem. I can send you a link if you want.

**Comment by adomasven** [comment]
Please post to [Zotero forums](forums.zotero.org) for further discussion and debugging.
