### ISSUE TITLE
Allow customization of the Google Docs hotkey

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-google-docs-integration#24]
At least as a hidden pref to start for advanced users. We can expose it as a JSON object for InputEvent:
```js
// Win/Linux
{ctrlKey: true, altKey: true, key: 'c'};
// macOS
{metaKey: true, ctrlKey: true, key: 'c'};
```

When testing I noticed that on macOS certain modifier combinations were not available and different combinations were available on different browsers: Chrome, Firefox and Safari. Meta-Ctrl was the only one working on them all which was why I settled for it. Thus exposing this option to users will also make it possible to break the shortcut completely or override Google Docs' own shortcuts.

**Comment by bjohas** [comment]
The current short cut on Mac also conflicts with one of the Google docs shortcuts (next suggestion) so it would be really great to have this hidden pref implemented!

**Comment by bjohas** [comment]
Thank you! How do I access this?

**Comment by adomasven** [comment]
This is still pending under a Pull Request https://github.com/zotero/zotero-connectors/pull/275. You can subscribe to the notifications there. It will be available in the connector beta shortly after the merge (the connector beta is only available on Firefox, and Firefox has only added browser extension shortcut support in their 66 Beta as well, so keep that in mind when testing) and at some not-distant future from the merge in the stable version.

**Comment by bjohas** [comment]
Ah ok - so this won't work for Chrome yet?

**Comment by adomasven** [comment]
Not until it is released, no.

**Comment by adomasven** [comment]
Now available in the <a href="https://www.zotero.org/support/dev_builds">Zotero Connector Beta</a>

**Comment by bjohas** [comment]
@adomasven Thank you - please do let us know when it's released in the Chrome connector as well!

**Comment by bjohas** [comment]
Hello,

Is it possible that this has stopped working? I recently re-adjusted the preference for the hotkey to no effect.

v. 5.0.56 on Chrome.

Thanks!

**Comment by bjohas** [comment]
Available in main connector release since March 2019.

In case anybody is wondering for Chrome: Go to your extensions in Chrome, then the Zotero extension, then Extension options, then Advanced > Google Docs integration. Change keyboard shortcut and reload any open google docs for this to take effect.

It doesn't seem to be possible to disable the shortcut (without disabling google docs integration), but it is possible to adjust it now - thank you so much!
