### ISSUE TITLE
Stop making the progress window change/highlight windows

### ISSUE THREAD

**Issue by MavropaliasG** [zotero/zotero-google-docs-integration#26]
Thank you for developing Zotero.

When I add/change a citation in G Docs I switch to another window to work there as it takes time, once the progress is finished and the progress window of zotero disappears, it also brings G Docs to the front. This is annoying and it disrupts workflow, it shouldn't do anything to the active window.

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

We are not going to change it as not returning the focus back to the Google Docs tab and window would be too confusing when initially using this feature, especially for new users
