### ISSUE TITLE
Move "Export document…" to Zotero menu

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#30]

**Comment by dstillman** [comment]
This is now [implemented](https://github.com/zotero/zotero-google-docs-integration/commit/cc4d3a44895122a1aeb408cf89bc552ca7aa7eff), but it's skipping the confirmation dialog, which is fairly important here. In the prefs that's a XUL prompt, but can we show the same thing as a connector prompt?

**Comment by dstillman** [comment]
(Or, I guess, do the same thing we do for import and show it as (I think) a child of the red bar window?)

**Comment by adomasven** [comment]
> This is now implemented, but it's skipping the confirmation dialog, which is fairly important here. In the prefs that's a XUL prompt, but can we show the same thing as a connector prompt?

Addressed in https://github.com/zotero/zotero/commit/96a0b771928f8c9039ce4b864b0e3c3aa3cd05cd
