### ISSUE TITLE
Embedded gdocs (e.g. in Dropbox) support

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-google-docs-integration#32]
Looking at the dropbox embedded gdocs raises some questions on whether this is possible, since you cannot inspect the contents of the frame, but we should investigate this further, particularly if there is increased interest.

**Comment by thBuchner** [comment]
There is/was? a similar problem with grammarly.
It would be wonderful if this could be fixed!
https://www.dropboxforum.com/t5/Dropbox-installs-integrations/Grammarly-does-not-work-on-Dropbox-Google-Doc/td-p/357064

**Comment by dstillman** [comment]
Apparently no longer relevant: https://forums.zotero.org/discussion/comment/444030/#Comment_444030
