### ISSUE TITLE
Notify about broken citation links

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-google-docs-integration#36]
Right now when the backend finds a Zotero link without corresponding field code it silently unlinks the citation without warning. This is rarely unintentional, however it seems that in some instances field copying fails and users end up with unlinked citations. 

Throwing a full on error on an update is not a great solution, since a single document update might reveal multiple broken links and an user might need to issue multiple new transactions to fix that.

We should look into marking broken citations with a different colour as well as adding a Zotero notification-popover UI icon to Google Docs somewhere, where we could show notifications for each unlinked citation and allow users to quickly navigate to them. Unfortunately highlighting text in the editor is rather unreliable, but any indication of broken links is better than nothing.

This would allow users to review broken citations post doc-update. We probably wouldn't preserve these notifications between sessions, but anything is better than the current situation.

**Comment by TMiguelT** [comment]
Should this be closed?

**Comment by adomasven** [comment]
Yep, I thought a comment with "Closes #commit-number" would close it automatically. Like it does for the PR message and commit messages.
