### ISSUE TITLE
Cut and Paste converts inline citation to plain text

### ISSUE THREAD

**Issue by yusufyilmaz** [zotero/zotero-google-docs-integration#37]
Hi respective developers!

I have an issue on google doc using Zotero. When I cut and paste citation or move within the page, Zotero cannot handle the citation anymore and converts inline citation to a plain text. It also removes the reference from bibliography. I have done research on Zotero forums and it seems Zotero does not support cut and paste or move text on google docs. Is there any roadmap to support within the google docs?

Thank you

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

This was an early limitation of the Google Docs support that was resolved a while back, as long the person copying has the Zotero Connector installed. If you're having trouble, post to the Zotero Forums.
