### ISSUE TITLE
Orphaned citation edit prompt sometimes appears twice

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#45]
After clicking "Edit with Zotero" on an unlinked citation and clicking "Relink Citation" (previously "OK") in the prompt, the prompt is often appearing a second time for me. I have to click the button a second time for the citation dialog to appear.

**Comment by adomasven** [comment]
I cannot reproduce this unless I double-click "Edit with Zotero", and even then it seems to be something else than what you're describing. Can you provide a sample doc? Screenshots?

**Comment by dstillman** [comment]
I shared the doc.
