### ISSUE TITLE
Export to PDF without copying document

### ISSUE THREAD

**Issue by TMiguelT** [zotero/zotero-google-docs-integration#47]
Currently the workflow for exporting to PDF is quite painful. You have to File → Make a Copy, choose a name for the copy, then File → Download. And then presumably delete the copy, because it's basically useless to keep around.

Does Google Docs provide the mechanism for a plugin to produce a file download? If so, is it possible to have a "download unlinked" option that combines the above process into one function that produces the final PDF?

**Comment by adomasven** [comment]
Please post all bug reports and feature requests to [Zotero forums](forums.zotero.org). See https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

This isn't possible.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/85403/google-docs-export-to-pdf-without-copying-document
