### ISSUE TITLE
Potential issues with new Google Docs move to Canvas

### ISSUE THREAD

**Issue by veale** [zotero/zotero-google-docs-integration#54]
Google Docs has just announced a controversial switch to canvas rendering (https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html, see controversy and impact on add-ons https://twitter.com/MidasNouwens/status/1392756740962332674). There seems to be a risk this will break (parts of) the Zotero plug-in given its front-end elements.

**Comment by adomasven** [comment]
Thanks. We are aware of this but currently don't have much to work with. Our plugin doesn't rely on reading the contents of the document as they are rendered in the browser itself. If the rest of the UI is not moved to canvas rendering, which it doesn't seem it will, it shouldn't be too hard to make the necessary changes for continued plugin support.

**Comment by adomasven** [comment]
I've tested the plugin in canvas rendering mode and it works without modification. Great news!
