### ISSUE TITLE
Show warning when trying to export linked doc

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#6]
Because of how we store data, citations in exported PDFs (and maybe other formats) are links to useless zotero.org URLs, and the actual links in the document don't work. This makes exported documents pretty inappropriate for any sort of submission.

If possible, we should intercept "Download as" attempts and show a warning when the document is still linked that says to create a copy, unlink that one, and then export that version.

**Comment by adomasven** [comment]
Just to note: we don't know whether the document contains Zotero citations until the user puts their cursor on at least one of them, so if someone just opens the doc and immediately downloads, we won't be able to prompt them.

**Comment by adomasven** [comment]
You will probably want to adjust [the text](https://github.com/adomasven/zotero-google-docs-integration/blob/ac4a3c93e482fbd50f1f49005af483390158fafe/src/connector/ui.jsx#L103-L114)

![image](https://user-images.githubusercontent.com/5899315/42950206-28893194-8b7c-11e8-856a-470e11bb29ac.png)
