### ISSUE TITLE
Show download warning every time

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#7]
Right now the download warning is only shown once.  Since you quite likely shouldn't be generating copies from the linked version, you could easily skip past the message without reading it the first time, and if you have a good reason it's just one extra click, I think it'd make sense to show the warning every time.

**Comment by adomasven** [comment]
It's only cached for the current session (i.e. a refresh resets the warning), but I guess there's no reason not to show it every time.
