### ISSUE TITLE
"An API change has caused this script to stop working"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#72]
New error, but only one user seems to have encountered it so far:

```
Error: An API change has caused this script to stop working. Section #1 of type UNSUPPORTED has no .getParagraphs() method. Stopping script. at Code:848 (iterateSection)

at .Code:954
at .Code:844
at .Code:115
at undefined. ( [Code:414](https://console.cloud.google.com/debug?referrer=fromlog&file=Code&line=414&authuser=0&project=project-id-3391180223009607478) )
at .Code:75
```

Looks like this error is from our code:

https://github.com/zotero/zotero-google-docs-integration/blob/c54ed2b7015fcc2667e0c2af1acc8a29be448fb2/src/apps-script/Code.js#L844-L853

I assume in this case the error message is misleading and this is just something unexpected being passed as `section`?

**Comment by adomasven** [comment]
Fixed by fc841120711cd122e045baca6f9ddacc775fa742
