### ISSUE TITLE
Error when variable chips are added to document

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-google-docs-integration#73]
https://forums.zotero.org/discussion/106567/google-docs-plugin-throws-error-when-variables-are-added-in-document

I didn't test, but it includes a test document

**Comment by dstillman** [comment]
Oh, but the feature is only available from a school or work account, apparently, so might be hard to test…

**Comment by adomasven** [comment]
Fixed by fc841120711cd122e045baca6f9ddacc775fa742
