### ISSUE TITLE
[Safari] Authentication fails with the auth window staying open

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-google-docs-integration#75]
First report on Oct 25. I cannot seem to reproduce it. Occurs on various macOS versions and Safari 17. Users are not following up with troubleshooting help.

https://forums.zotero.org/discussion/108849/zotero-for-google-doc-doesnt-work-on-safari
https://forums.zotero.org/discussion/108926/zotero-connector-for-google-docs-not-working
https://forums.zotero.org/discussion/109104/zotero-connecter-not-working-with-google-docs-on-safari
https://forums.zotero.org/discussion/109255/zotero-not-integrating-with-google-docs-on-mac
https://forums.zotero.org/discussion/109260/safari-zotero-connector-citation-generator-keeps-crashing
https://forums.zotero.org/discussion/109340/report-id-782775337

**Comment by dstillman** [comment]
Zotero 6.0.28 on October 11 had an updated Safari Connector. The last one was from April.

**Comment by adomasven** [comment]
https://forums.zotero.org/discussion/111318/zotero-connector-error

**Comment by adomasven** [comment]
Turns out this is caused by users not having enabled Zotero Connector to run on zotero.org via extension run-scope management. Updated the connector auth completion page with instructions on how to enable it https://www.zotero.org/connector_auth_complete
