### ISSUE TITLE
After adding citation, main window is hidden

### ISSUE THREAD

**Issue by leoauri** [zotero/zotero-google-docs-integration#76]
## What happens:
- Editing a document in Google Docs. Google Docs and Zotero main window are in different desktops in MacOS
- Add a citation to document with hotkey
- Move to desktop with Zotero main window, it is gone
- Experience confusion and mental overhead as I start thinking about how to find Zotero again

## Expected behaviour:
- Add a citation to document
- Move to desktop where Zotero was displayed
- Directly see & access Zotero main window

## Versions:
- MacOS 13.5 (22G74)
- Zotero 6.0.30
- Firefox 119.0.1 (64-bit)

Thanks :)

**Comment by dstillman** [comment]
Please post all support requests to the Zotero Forums.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
